name: hm_demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # 放宽SDK版本要求

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  flutter_riverpod: ^2.4.9  # 锁定稳定版本
  riverpod_annotation: ^2.3.4
  dio: ^5.4.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/mine/
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"        # 生成安卓图标的文件名
  # ios: true                       # 是否生成iOS图标
  image_path: "assets/icon.png" 
